# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ActionMailer::Collector; end
module RSpec::Rails::ViewExampleGroup; end
module RSpec::Rails::ViewExampleGroup::ExampleMethods; end
module T::Private::Methods::Signature; end