require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-sorbet
  - rubocop-thread_safety
  - rubocop-i18n
  - rubocop-graphql

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

GraphQL/ExtractType:
  Enabled: false

GraphQL/GraphQL/ExtractInputType:
  Enabled: false

Layout/AccessModifierIndentation:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Layout/ArrayAlignment:
  Enabled: false

Layout/BlockEndNewline:
  Enabled: false

Layout/CaseIndentation:
  Enabled: false

Layout/CommentIndentation:
  Enabled: false

Layout/ElseAlignment:
  Enabled: false

Layout/EndAlignment:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Layout/IndentationConsistency:
  Enabled: false

Layout/IndentationStyle:
  Enabled: false

Layout/IndentationWidth:
  Enabled: false

Layout/LineEndStringConcatenationIndentation:
  Enabled: false

Layout/LineLength:
  Enabled: false

Layout/MultilineBlockLayout:
  Enabled: false

Layout/ParameterAlignment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockNesting:
  Max: 4

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Performance/CollectionLiteralInLoop: # disabled to allow [:aaa, :bbb].each when doesn't affect performance
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

RSpec/ChangeByZero: # Currently crashes rubocop, remove once fix is available
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Enabled: false

RSpec/RepeatedExampleGroupDescription: # reporting false errors
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashAsLastArrayItem:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Next:
  Enabled: false

Style/OpenStructUse:
  Enabled: false