# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.2'

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem 'rails', '~> 7.0.8', '>= 7.0.8.1'

# Use postgresql as the database for Active Record
gem 'pg', '~> 1.1'

# Use the Puma web server [https://github.com/puma/puma]
gem 'puma', '~> 5.0'

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
# gem "jbuilder"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
gem 'image_processing', '~> 1.2'

gem 'bcrypt'

gem 'sorbet-runtime' # Sorbet Type Checking (Runtime Only)

gem 'goldiloader' # auto includes relationships in models
gem 'sqids'
gem 'unsplash_image' # creates product images based on product name
gem 'workers' # multithreading, used during seeding for images

# cs
gem 'graphql' # for graphql queries and mutations
gem 'jwt' # JWT auth token for graphql authentication
gem 'rack-cors' # CORS settings for api

group :development, :test do
	# See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
	gem 'debug', platforms: %i[mri mingw x64_mingw]

	gem 'active_record_query_trace' # backtrace queries in code
	gem 'binding_of_caller' # grab bindings from higher up the call stack and evaluate code in that context
	gem 'bullet' # monitors query performance and notifies you when there are performance issues
	gem 'spring' # speeds up development by keeping your application running in the background so you don't need to boot it every time you run a test, rake task or migration.

	gem 'dotenv-rails' # .env config files support
	gem 'require_reloader'

	# Rubcop
	gem 'rubocop'
	gem 'rubocop-graphql', require: false
	gem 'rubocop-i18n', require: false
	gem 'rubocop-performance', require: false
	gem 'rubocop-rails', require: false
	gem 'rubocop-rake', require: false
	gem 'rubocop-rspec', require: false
	gem 'rubocop-sorbet', require: false
	gem 'rubocop-thread_safety', require: false
end

group :test do
	# RSPEC
	gem 'fabrication' # creates models, similar to factory bot#
	gem 'ffaker'
	gem 'parallel_tests'
	gem 'rspec-collection_matchers' # collection matchers
	gem 'rspec-graphql_matchers'
	gem 'rspec-rails' # default testing library
	gem 'shoulda'
	gem 'shoulda-matchers' # shoulda matchers for model tests
	gem 'stackprof'
	gem 'test-prof', '~> 1.0'

	# Testing
	gem 'simplecov' # code coverage inspection
end

group :development do
	# Speed up commands on slow machines / big apps [https://github.com/rails/spring]
	# gem "spring"
	gem 'brakeman', require: false # scans code and gems for issues ---- use brakeman to scan
	gem 'bundle-audit' # use bundle-audit to scan
	gem 'dawnscanner', require: false # use "dawn ." to scan
	gem 'meta_request' # Supporting gem for Rails Panel (Google Chrome extension for Rails development).
	gem 'rails_best_practices', require: false # scans code for issues ---- use "rails_best_practices ." to scan
	gem 'rubycritic', require: false # scans code for issues

	gem 'graphiql-rails' # Graphql web interface
	gem 'sprockets-rails' # For graphiql web interface only

	# -- Type Checking --
	gem 'sorbet' # Type Checking
	gem 'spoom', require: false # Sorbet: Additional commands
	gem 'tapioca', require: false # Sorbet: Generates rbi files
end
