# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `cvss` gem.
# Please instead update this file by running `bin/tapioca gem cvss`.

# source://cvss//lib/cvss/version.rb#1
module Cvss; end

# source://cvss//lib/cvss.rb#6
class Cvss::Engine
  include ::Cvss::Parser
  include ::Cvss::Helpers

  # source://cvss//lib/cvss.rb#10
  def score(vector); end
end

# source://cvss//lib/cvss/helpers.rb#2
module Cvss::Helpers
  # source://cvss//lib/cvss/helpers.rb#9
  def data_availability; end

  # source://cvss//lib/cvss/helpers.rb#6
  def data_confidentiality; end

  # source://cvss//lib/cvss/helpers.rb#3
  def data_integrity; end
end

# source://cvss//lib/cvss/parser.rb#2
module Cvss::Parser
  # Returns the value of attribute base.
  #
  # source://cvss//lib/cvss/parser.rb#4
  def base; end

  # It parses a string and it says if it's a good CVSS vector or not.
  #
  # source://cvss//lib/cvss/parser.rb#7
  def parse(string); end

  private

  # AV:N/AC:L/Au:N/C:N/I:N/A:C
  #
  # source://cvss//lib/cvss/parser.rb#17
  def parse_base(tokens); end
end

# source://cvss//lib/cvss/version.rb#2
Cvss::VERSION = T.let(T.unsafe(nil), String)
