# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `logger-colors` gem.
# Please instead update this file by running `bin/tapioca gem logger-colors`.

# source://logger-colors//lib/logger/colors.rb#9
class Logger
  # source://logger-colors//lib/logger/colors.rb#41
  def format_message(level, *args); end
end

# source://logger-colors//lib/logger/colors.rb#10
module Logger::Colors; end

# source://logger-colors//lib/logger/colors.rb#14
Logger::Colors::BLACK = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#18
Logger::Colors::BLUE = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#17
Logger::Colors::BROWN = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#20
Logger::Colors::CYAN = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#22
Logger::Colors::DARK_GRAY = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#16
Logger::Colors::GREEN = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#26
Logger::Colors::LIGHT_BLUE = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#28
Logger::Colors::LIGHT_CYAN = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#21
Logger::Colors::LIGHT_GRAY = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#24
Logger::Colors::LIGHT_GREEN = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#27
Logger::Colors::LIGHT_PURPLE = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#23
Logger::Colors::LIGHT_RED = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#13
Logger::Colors::NOTHING = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#19
Logger::Colors::PURPLE = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#15
Logger::Colors::RED = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#31
Logger::Colors::SCHEMA = T.let(T.unsafe(nil), Hash)

# source://logger-colors//lib/logger/colors.rb#11
Logger::Colors::VERSION = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#29
Logger::Colors::WHITE = T.let(T.unsafe(nil), String)

# source://logger-colors//lib/logger/colors.rb#25
Logger::Colors::YELLOW = T.let(T.unsafe(nil), String)
