# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `unsplash_image` gem.
# Please instead update this file by running `bin/tapioca gem unsplash_image`.

# source://unsplash_image//lib/unsplash_image/version.rb#1
module UnsplashImage
  extend ::UnsplashImage::Download
end

# source://unsplash_image//lib/unsplash_image/download.rb#5
module UnsplashImage::Download
  # source://unsplash_image//lib/unsplash_image/download.rb#6
  def tempfile(size: T.unsafe(nil), filename: T.unsafe(nil), tags: T.unsafe(nil)); end
end

# source://unsplash_image//lib/unsplash_image/helper.rb#2
module UnsplashImage::Helper
  extend ::UnsplashImage::Helper

  # source://unsplash_image//lib/unsplash_image/helper.rb#7
  def unsplash_image_url(size: T.unsafe(nil), tags: T.unsafe(nil)); end
end

# source://unsplash_image//lib/unsplash_image/helper.rb#5
UnsplashImage::Helper::BASE = T.let(T.unsafe(nil), String)

# source://unsplash_image//lib/unsplash_image/railtie.rb#2
class UnsplashImage::Railtie < ::Rails::Railtie; end

# source://unsplash_image//lib/unsplash_image/version.rb#2
UnsplashImage::VERSION = T.let(T.unsafe(nil), String)
